# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(725, 309)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 704, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.namaLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.namaLabel.setObjectName("namaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.namaLabel)
        self.QLineEdit_nama = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.QLineEdit_nama.setObjectName("QLineEdit_nama")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.QLineEdit_nama)
        self.nIMLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.nIMLabel.setObjectName("nIMLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nIMLabel)
        self.QLineEdit_nim = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.QLineEdit_nim.setObjectName("QLineEdit_nim")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.QLineEdit_nim)
        self.prodiLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.prodiLabel.setObjectName("prodiLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.prodiLabel)
        self.QLineEdit_prodi = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.QLineEdit_prodi.setObjectName("QLineEdit_prodi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.QLineEdit_prodi)
        self.hobiLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.hobiLabel.setObjectName("hobiLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.hobiLabel)
        self.QLineEdit_hobi = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.QLineEdit_hobi.setObjectName("QLineEdit_hobi")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.QLineEdit_hobi)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.QpushButton_tambahkan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.QpushButton_tambahkan.setObjectName("QpushButton_tambahkan")
        self.horizontalLayout_2.addWidget(self.QpushButton_tambahkan)
        self.QpushButton_hapus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.QpushButton_hapus.setObjectName("QpushButton_hapus")
        self.horizontalLayout_2.addWidget(self.QpushButton_hapus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.QtableWidget_biodata = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.QtableWidget_biodata.setMinimumSize(QtCore.QSize(400, 0))
        self.QtableWidget_biodata.setObjectName("QtableWidget_biodata")
        self.QtableWidget_biodata.setColumnCount(4)
        self.QtableWidget_biodata.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.QtableWidget_biodata.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtableWidget_biodata.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtableWidget_biodata.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtableWidget_biodata.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.QtableWidget_biodata)
        self.Qlabel_warning = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Qlabel_warning.setObjectName("Qlabel_warning")
        self.verticalLayout_2.addWidget(self.Qlabel_warning)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Biodata"))
        self.namaLabel.setText(_translate("Form", "Nama"))
        self.nIMLabel.setText(_translate("Form", "NIM"))
        self.prodiLabel.setText(_translate("Form", "Prodi"))
        self.hobiLabel.setText(_translate("Form", "Hobi"))
        self.QpushButton_tambahkan.setText(_translate("Form", "Tambahkan"))
        self.QpushButton_hapus.setText(_translate("Form", "Hapus"))
        item = self.QtableWidget_biodata.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nama"))
        item = self.QtableWidget_biodata.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NIM"))
        item = self.QtableWidget_biodata.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Prodi"))
        item = self.QtableWidget_biodata.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Hobi"))
        self.Qlabel_warning.setText(_translate("Form", "Warning"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

